from __future__ import annotations

# Keep finance vocabulary centralized so relevance tuning does not require
# edits to ticker profile assembly logic.
FINANCE_CONTEXT_TERMS: tuple[str, ...] = (
    "stock",
    "stocks",
    "shares",
    "equity",
    "market",
    "markets",
    "investor",
    "investors",
    "investing",
    "investment",
    "earnings",
    "revenue",
    "profit",
    "margin",
    "valuation",
    "guidance",
    "forecast",
    "outlook",
    "estimate",
    "estimates",
    "analyst",
    "analysts",
    "upgrade",
    "downgrade",
    "price",
    "target",
    "volatility",
    "volume",
    "liquidity",
    "buyback",
    "dividend",
    "cashflow",
    "balance",
    "sheet",
    "debt",
    "quarter",
    "fiscal",
    "company",
    "business",
    "corporate",
    "sector",
    "industry",
    "guidance",
    "fundamentals",
    "risk",
    "return",
    "capital",
    "bullish",
    "bearish",
    "long",
    "short",
    "calls",
    "puts",
    "options",
    "trading",
    "trader",
    "portfolio",
)


def finance_context_text() -> str:
    return " ".join(FINANCE_CONTEXT_TERMS)
