from __future__ import annotations

import hashlib
import random


def _score_band(score: float) -> str:
    if score >= 0.20:
        return "bullish"
    if score <= -0.20:
        return "bearish"
    return "neutral"


_KEYWORD_BANK: dict[str, dict[str, list[str]]] = {
    "TSLA": {
        "bullish": [
            "record deliveries",
            "energy storage growth",
            "fsd progress",
            "margin recovery",
            "robotaxi optionality",
            "china demand rebound",
            "factory efficiency",
            "price momentum",
        ],
        "neutral": [
            "delivery watch",
            "margin trend",
            "pricing strategy",
            "factory utilization",
            "fsd timeline",
            "battery costs",
            "china mix",
            "next earnings",
        ],
        "bearish": [
            "delivery slowdown",
            "margin pressure",
            "price-cut risk",
            "ev competition",
            "demand uncertainty",
            "execution risk",
            "macro headwinds",
            "multiple compression",
        ],
    },
    "AAPL": {
        "bullish": [
            "services growth",
            "buyback support",
            "iphone demand",
            "ecosystem moat",
            "wearables strength",
            "premium pricing power",
            "cash flow stability",
            "ai product cycle",
        ],
        "neutral": [
            "product cycle timing",
            "services mix",
            "china exposure",
            "upgrade cadence",
            "gross margin",
            "guidance watch",
            "valuation balance",
            "supply chain checks",
        ],
        "bearish": [
            "china weakness",
            "upgrade fatigue",
            "regulatory overhang",
            "growth deceleration",
            "hardware saturation",
            "margin squeeze risk",
            "innovation concerns",
            "demand softness",
        ],
    },
    "MSFT": {
        "bullish": [
            "azure acceleration",
            "copilot adoption",
            "enterprise stickiness",
            "cloud margin leverage",
            "ai monetization",
            "recurring revenue",
            "strong guidance",
            "platform breadth",
        ],
        "neutral": [
            "azure growth pace",
            "ai spend payoff",
            "seat expansion",
            "cloud optimization",
            "guidance quality",
            "enterprise demand",
            "valuation check",
            "margin trajectory",
        ],
        "bearish": [
            "cloud slowdown",
            "ai cost burden",
            "enterprise budget cuts",
            "multiple risk",
            "competition pressure",
            "growth normalization",
            "capex overhang",
            "execution concerns",
        ],
    },
    "NVDA": {
        "bullish": [
            "datacenter demand",
            "ai chip leadership",
            "supply expansion",
            "pricing power",
            "blackwell ramp",
            "hyperscaler orders",
            "margin strength",
            "earnings upside",
        ],
        "neutral": [
            "supply-demand balance",
            "next-gen ramp",
            "order visibility",
            "capacity planning",
            "valuation sensitivity",
            "customer concentration",
            "guidance watch",
            "margin durability",
        ],
        "bearish": [
            "valuation stretch",
            "demand digestion",
            "export restrictions",
            "competition risk",
            "order volatility",
            "capex cycle peak",
            "inventory risk",
            "multiple compression",
        ],
    },
    "AMZN": {
        "bullish": [
            "aws stabilization",
            "ads momentum",
            "prime retention",
            "operating leverage",
            "logistics efficiency",
            "cash flow upside",
            "retail margin gains",
            "ai services tailwind",
        ],
        "neutral": [
            "aws growth rate",
            "retail profitability",
            "capex discipline",
            "ad demand trend",
            "consumer spending",
            "fulfillment costs",
            "guidance monitor",
            "valuation range",
        ],
        "bearish": [
            "aws slowdown",
            "consumer softness",
            "margin pressure",
            "high capex burden",
            "competition intensity",
            "execution risk",
            "macro uncertainty",
            "profit volatility",
        ],
    },
    "GOOGL": {
        "bullish": [
            "search resilience",
            "youtube monetization",
            "cloud improvement",
            "gemini traction",
            "ad pricing strength",
            "operating discipline",
            "buyback support",
            "ai integration",
        ],
        "neutral": [
            "ad demand trend",
            "cloud profitability",
            "ai rollout pace",
            "traffic acquisition costs",
            "regulatory backdrop",
            "youtube growth",
            "margin watch",
            "guidance signals",
        ],
        "bearish": [
            "antitrust overhang",
            "search share concerns",
            "ad slowdown",
            "ai cannibalization risk",
            "cloud competition",
            "regulatory pressure",
            "margin compression",
            "growth deceleration",
        ],
    },
    "META": {
        "bullish": [
            "ad efficiency gains",
            "reels monetization",
            "engagement growth",
            "cost discipline",
            "ai ad tools",
            "cash generation",
            "buyback capacity",
            "platform scale",
        ],
        "neutral": [
            "ad demand watch",
            "reality labs spend",
            "engagement trend",
            "reels mix shift",
            "ai infra costs",
            "regulatory risk",
            "margin balance",
            "next guidance",
        ],
        "bearish": [
            "ad cyclicality",
            "high ai spend",
            "privacy headwinds",
            "regulatory scrutiny",
            "margin pressure",
            "metaverse drag",
            "growth normalization",
            "multiple risk",
        ],
    },
    "BRK.B": {
        "bullish": [
            "insurance float strength",
            "cash optionality",
            "disciplined capital allocation",
            "quality portfolio",
            "defensive earnings mix",
            "buyback flexibility",
            "long-term compounder",
            "balance-sheet strength",
        ],
        "neutral": [
            "cash deployment timing",
            "insurance pricing cycle",
            "rail volume trends",
            "portfolio mark-to-market",
            "rate sensitivity",
            "buyback pace",
            "earnings mix",
            "valuation check",
        ],
        "bearish": [
            "cash drag risk",
            "insurance catastrophe risk",
            "cyclical subsidiaries",
            "limited growth catalysts",
            "market exposure",
            "rate reversal risk",
            "underperformance concern",
            "valuation premium",
        ],
    },
    "JPM": {
        "bullish": [
            "net interest income strength",
            "credit quality resilience",
            "capital return capacity",
            "trading revenue upside",
            "scale advantage",
            "deposit franchise",
            "fee income stability",
            "balance-sheet quality",
        ],
        "neutral": [
            "net interest margin",
            "loan growth trend",
            "credit provisioning",
            "investment banking pipeline",
            "capital requirements",
            "deposit pricing",
            "guidance tone",
            "macro sensitivity",
        ],
        "bearish": [
            "credit deterioration risk",
            "net interest margin compression",
            "regulatory capital pressure",
            "loan demand softness",
            "trading volatility",
            "macro downturn risk",
            "provision build-up",
            "earnings uncertainty",
        ],
    },
    "V": {
        "bullish": [
            "payment volume growth",
            "cross-border recovery",
            "network moat",
            "high margins",
            "cashless adoption",
            "operating leverage",
            "steady buybacks",
            "global acceptance",
        ],
        "neutral": [
            "cross-border trend",
            "consumer spend mix",
            "merchant pricing",
            "volume growth pace",
            "fx impact",
            "regulatory watch",
            "margin consistency",
            "guidance outlook",
        ],
        "bearish": [
            "spending slowdown",
            "regulatory fee pressure",
            "fintech competition",
            "cross-border weakness",
            "volume deceleration",
            "multiple compression",
            "macro sensitivity",
            "growth concerns",
        ],
    },
    "MA": {
        "bullish": [
            "cross-border momentum",
            "payment network strength",
            "high-margin model",
            "services expansion",
            "cashless tailwind",
            "volume acceleration",
            "pricing durability",
            "earnings visibility",
        ],
        "neutral": [
            "consumer spend trends",
            "cross-border pace",
            "service revenue mix",
            "fx effects",
            "volume seasonality",
            "cost discipline",
            "valuation balance",
            "guidance watch",
        ],
        "bearish": [
            "spending deceleration",
            "fee regulation risk",
            "competitive pressure",
            "cross-border softness",
            "growth normalization",
            "valuation risk",
            "macro uncertainty",
            "earnings pressure",
        ],
    },
    "WMT": {
        "bullish": [
            "same-store sales strength",
            "traffic gains",
            "grocery leadership",
            "e-commerce leverage",
            "inventory discipline",
            "membership growth",
            "defensive demand",
            "margin expansion",
        ],
        "neutral": [
            "consumer trade-down",
            "basket size trend",
            "inventory levels",
            "labor cost pressure",
            "omnichannel mix",
            "holiday outlook",
            "guidance focus",
            "gross margin trend",
        ],
        "bearish": [
            "margin squeeze",
            "consumer weakness",
            "cost inflation",
            "pricing pressure",
            "discretionary softness",
            "execution risk",
            "profitability concerns",
            "guidance caution",
        ],
    },
    "LLY": {
        "bullish": [
            "obesity-drug demand",
            "pipeline depth",
            "trial momentum",
            "pricing power",
            "revenue acceleration",
            "market share gains",
            "earnings upgrades",
            "innovation premium",
        ],
        "neutral": [
            "supply constraints",
            "trial readouts",
            "pipeline milestones",
            "pricing debate",
            "launch execution",
            "regulatory timeline",
            "valuation sensitivity",
            "guidance watch",
        ],
        "bearish": [
            "valuation stretch",
            "supply bottlenecks",
            "trial risk",
            "pricing pressure",
            "competitive entrants",
            "regulatory uncertainty",
            "growth expectations reset",
            "multiple risk",
        ],
    },
    "XOM": {
        "bullish": [
            "oil price support",
            "upstream strength",
            "cash flow generation",
            "shareholder returns",
            "production growth",
            "balance-sheet durability",
            "dividend support",
            "discipline on capex",
        ],
        "neutral": [
            "commodity volatility",
            "refining margins",
            "production guidance",
            "capex plans",
            "energy demand outlook",
            "macro sensitivity",
            "inventory signals",
            "cash return pace",
        ],
        "bearish": [
            "oil price weakness",
            "refining margin pressure",
            "demand slowdown",
            "commodity downturn",
            "profit cyclicality",
            "energy transition risk",
            "earnings decline risk",
            "cash flow pressure",
        ],
    },
    "JNJ": {
        "bullish": [
            "medtech growth",
            "pharma resilience",
            "diversified portfolio",
            "defensive earnings",
            "pipeline optionality",
            "cash flow stability",
            "balance-sheet quality",
            "dividend consistency",
        ],
        "neutral": [
            "pipeline readouts",
            "medtech demand trend",
            "pricing environment",
            "litigation updates",
            "segment mix",
            "guidance quality",
            "margin trajectory",
            "capital allocation",
        ],
        "bearish": [
            "litigation overhang",
            "pipeline setbacks",
            "pricing pressure",
            "growth slowdown",
            "margin pressure",
            "regulatory scrutiny",
            "execution risk",
            "earnings uncertainty",
        ],
    },
    "ORCL": {
        "bullish": [
            "cloud backlog growth",
            "ai infrastructure demand",
            "database stickiness",
            "enterprise contracts",
            "margin leverage",
            "recurring revenue",
            "bookings momentum",
            "cash generation",
        ],
        "neutral": [
            "cloud conversion pace",
            "bookings visibility",
            "capex needs",
            "contract timing",
            "customer migrations",
            "guidance watch",
            "margin stability",
            "valuation balance",
        ],
        "bearish": [
            "cloud execution risk",
            "competitive pressure",
            "slower bookings",
            "integration challenges",
            "margin compression",
            "growth disappointment",
            "capex burden",
            "multiple risk",
        ],
    },
    "AVGO": {
        "bullish": [
            "ai networking demand",
            "custom silicon tailwind",
            "vmware synergy",
            "strong free cash flow",
            "margin durability",
            "enterprise demand",
            "earnings momentum",
            "shareholder returns",
        ],
        "neutral": [
            "integration progress",
            "ai demand pacing",
            "enterprise spend trend",
            "segment mix",
            "guidance tone",
            "margin path",
            "valuation checks",
            "deal execution",
        ],
        "bearish": [
            "integration risk",
            "demand cyclicality",
            "customer concentration",
            "margin pressure",
            "competition risk",
            "growth slowdown",
            "execution uncertainty",
            "valuation pullback",
        ],
    },
    "COST": {
        "bullish": [
            "membership renewal strength",
            "traffic resilience",
            "comp sales growth",
            "private-label momentum",
            "pricing power",
            "defensive retail demand",
            "operational efficiency",
            "steady margin profile",
        ],
        "neutral": [
            "comp trend watch",
            "membership fee timing",
            "consumer basket mix",
            "inventory management",
            "gross margin trend",
            "holiday demand",
            "guidance monitor",
            "valuation premium",
        ],
        "bearish": [
            "valuation premium risk",
            "consumer slowdown",
            "margin headwinds",
            "traffic normalization",
            "cost inflation pressure",
            "growth deceleration",
            "profitability risk",
            "multiple compression",
        ],
    },
    "NKE": {
        "bullish": [
            "brand strength",
            "inventory normalization",
            "d2c momentum",
            "gross margin recovery",
            "new product cycle",
            "international growth",
            "digital engagement",
            "turnaround traction",
        ],
        "neutral": [
            "inventory levels",
            "promotional activity",
            "china demand trend",
            "channel mix",
            "margin recovery pace",
            "product launches",
            "guidance tone",
            "consumer demand",
        ],
        "bearish": [
            "weak demand",
            "promotional pressure",
            "margin contraction",
            "inventory overhang",
            "execution risk",
            "competitive intensity",
            "turnaround uncertainty",
            "earnings pressure",
        ],
    },
    "PFE": {
        "bullish": [
            "oncology pipeline strength",
            "cost optimization",
            "late-stage catalysts",
            "cash flow support",
            "portfolio reshaping",
            "earnings stabilization",
            "dividend support",
            "valuation floor",
        ],
        "neutral": [
            "pipeline milestones",
            "revenue mix reset",
            "cost-cut progress",
            "guidance watch",
            "patent timeline",
            "deal integration",
            "margin outlook",
            "capital allocation",
        ],
        "bearish": [
            "patent cliff concerns",
            "revenue decline risk",
            "pipeline uncertainty",
            "pricing pressure",
            "post-vaccine reset",
            "margin pressure",
            "execution risk",
            "growth visibility low",
        ],
    },
}

_GENERIC_BANK: dict[str, list[str]] = {
    "bullish": [
        "upward momentum",
        "guidance beat",
        "strong demand",
        "margin expansion",
        "earnings upside",
        "positive revisions",
        "buying pressure",
        "bullish flow",
    ],
    "neutral": [
        "range-bound action",
        "mixed signals",
        "guidance watch",
        "macro sensitivity",
        "valuation check",
        "wait-and-see",
        "sideways sentiment",
        "balanced outlook",
    ],
    "bearish": [
        "downside risk",
        "earnings pressure",
        "margin squeeze",
        "weak demand",
        "negative revisions",
        "selling pressure",
        "macro headwinds",
        "bearish flow",
    ],
}


def select_signal_keywords(
    *, ticker: str, signal_score: float, hour_start_utc: int, limit: int = 3
) -> list[str]:
    """
    Demo keyword picker used for signal docs.

    - Picks from ticker-specific keyword banks using score band
    - Uses deterministic pseudo-random selection per (ticker, hour, band)
      so results feel dynamic across hours but stay stable inside one hour
    """
    clean_ticker = (ticker or "").strip().upper()
    band = _score_band(float(signal_score))
    candidates = _KEYWORD_BANK.get(clean_ticker, {}).get(band) or _GENERIC_BANK[band]

    pick_count = max(1, min(int(limit), len(candidates)))
    seed_bytes = f"{clean_ticker}|{hour_start_utc}|{band}".encode(
        "utf-8", errors="replace"
    )
    seed_int = int.from_bytes(hashlib.sha256(seed_bytes).digest()[:8], "big")
    rng = random.Random(seed_int)
    return rng.sample(candidates, pick_count)

