package com.sentrix.filtering_service_a.model.service_a;

public enum FilterReason {
  MISSING_REQUIRED_FIELD,
  INVALID_EVENT_TYPE,
  INVALID_SOURCE,
  MALFORMED_EVENT,
  EMPTY_TEXT,
  TOO_SHORT_TEXT,
  OVERSIZE_TRUNCATED,
  NON_TEXTUAL_CONTENT,
  TOO_OLD,
  FUTURE_TIMESTAMP,
  EXACT_DUP_EVENT_ID,
  EXACT_DUP_CONTENT,
  DENYLIST_DOMAIN,
  URL_SPAM_EXCESSIVE,
  SCAM_PHRASE_MATCH,
  AUTOMATED_SPAM_PATTERN,
  REPEATED_CHAR_SIGNAL,
  EXCESSIVE_EMOJI_SIGNAL,
  HIGH_CAPS_RATIO_SIGNAL,
  MULTI_TICKER_SPAM_SIGNAL,
  LOW_INFORMATION_SIGNAL,
  RAW_PARSE_FAIL,
  PIPELINE_CALL_FAIL
}
