export const DEFAULT_WATCHLIST: string[] = [
  "AAPL",
  "MSFT",
  "NVDA",
  "AMZN",
  "GOOGL",
  "META",
  "TSLA",
  "JPM",
  "XOM",
  "JNJ",
];

export const TICKER_NAME_MAP: Record<string, string> = {
  AAPL: "Apple",
  AMZN: "Amazon",
  AVGO: "Broadcom",
  "BRK.B": "Berkshire Hathaway",
  COST: "Costco",
  GOOGL: "Alphabet",
  JNJ: "Johnson & Johnson",
  JPM: "JPMorgan Chase",
  LLY: "Eli Lilly",
  MA: "Mastercard",
  META: "Meta Platforms",
  MSFT: "Microsoft",
  NKE: "Nike",
  NVDA: "NVIDIA",
  ORCL: "Oracle",
  PFE: "Pfizer",
  TSLA: "Tesla",
  V: "Visa",
  WMT: "Walmart",
  XOM: "Exxon Mobil",
};
